#!/bin/sh

### Init

## asdf

. /usr/local/opt/asdf/libexec/asdf.sh

## bookmarks

if [ -d "$HOME/.bookmarks" ]; then
  export CDPATH=".:$HOME/.bookmarks:/"
fi

### Evals

eval "$(direnv hook zsh)"

### Functions

## bookmarks

_add_bookmark () {
  local current_dir="$(pwd)"
  cd "$1" || return
  local bookmark_name=@"$2"
  local src="$(pwd)"
  ln -is "$src" ~/.bookmarks/"$bookmark_name"
  cd "$current_dir" || return
  echo "success added bookmark. ($bookmark_name to $src)"
}

_delete_bookmark () {
  local bookmark_name=@"$1"
  local bookmark_path=~/.bookmarks/"$bookmark_name"

  if [ ! -L "$bookmark_path" ]; then
    echo "no such link. ($bookmark_path)"
    echo "failed remove bookmark. ($bookmark_name)"
    return
  fi

  printf "remove %s?: " "$bookmark_name"
  read -r yn

  if [ ! "$yn" = "Y" ] && [ ! "$yn" = "y" ]; then
    echo "canceled remove bookmark. ($bookmark_name)"
    return
  fi

  local src="$(readlink "$bookmark_path")"
  unlink "$bookmark_path"
  echo "success remove bookmark. ($bookmark_name to $src)"
}

### Aliases

## cd

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

## git

alias g="git"
alias gb="g branch"
alias gd="g diff"
alias ga="g add"
alias gc="g commit"
alias gf="g fetch"
alias gst="g status"
alias gco="g checkout"
alias gcp="g cherry-pick"
alias grb="g rebase"

## docker

alias d="docker"
alias dc="docker compose"

## terraform

alias tf="terraform"

## bookmarks

alias goto="cd -P"
alias bl="ls ~/.bookmarks/"
alias bll="ls -l ~/.bookmarks/"
alias ba="_add_bookmark"
alias bd="_delete_bookmark"

## bundler

alias be="bundle exec"
alias bi="bundle install"
alias bu="bundle update"

### Envs

export EDITOR=vi
export VISUAL=vi
export PAGER=less

## go

export PATH="$PATH":"$(go env GOPATH)"/bin

### Final

[ -f ~/.zshrc.local ] && . ~/.zshrc.local

