#! /usr/bin/env sh

set -eu

if [ "$(sudo echo hi)" != hi ]; then
  echo "Cannot use sudo."
else
  sudo apt-get update
  sudo apt-get install build-essential curl file git procps zsh -y

  if (type "brew" > /dev/null 2>&1); then
    echo "skip brew installtion step"
  else
    echo "execute brew installtion step"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    . ~/.zshrc
  fi

  brew bundle --file ~/.Brewfile.ubuntu
  asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  asdf install nodejs latest
fi

