#! /usr/bin/env sh

set -eu

if [ "$(sudo echo hi)" != hi ]; then
  echo "Cannot use sudo."
else
  sudo apt-get update && sudo apt-get install -y \
    awscli \
    build-essential \
    curl \
    file \
    git \
    grep \
    jq \
    less \
    procps \
    vim \
    zsh \
    openssh-server

  # ssd setting
  sudo mkdir /var/run/sshd
  sudo /usr/sbin/sshd

  # install other tools
  sudo BINDIR=/usr/bin sh -c "$(curl -fsLS get.chezmoi.io)"

  # shell
  if [ -x "$(command -v zsh)" ]; then
    sudo chsh -s $(which zsh) $USER
  fi
fi

