#! /usr/bin/env sh

set -eu

if [ "$(sudo echo hi)" != hi ]; then
  echo "Cannot use sudo."
else
  sudo apt-get update && sudo apt-get install -y \
    awscli \
    build-essential \
    curl \
    file \
    git \
    grep \
    jq \
    less \
    procps \
    vim \
    zsh \
    openssh-server

  # ssd setting
  sudo mkdir /var/run/sshd
  sudo /usr/sbin/sshd

  # install other tools
  sudo env BINDIR="/usr/bin" sh -c "$(curl -fsLS get.chezmoi.io)"
  sudo env UV_INSTALL_DIR="/usr/bin" sh -c "$(curl -LsSf https://astral.sh/uv/install.sh)"
  sudo env PNPM_HOME="/usr/bin" sh -c "$(curl -LsSf https://get.pnpm.io/install.sh)"
  sudo env BIN_DIR="/usr/bin" sh -c "$(curl -sS https://starship.rs/install.sh)"
  sudo env BIN_DIR="/usr/bin" sh -c "$(curl -fsSL https://raw.githubusercontent.com/kiki-ki/rura/main/install.sh)"

  if [ -x "$(command -v pnpm)"]; then
    pnpm config set --location=global minimumReleaseAge 4320 # 3days
  fi

  # shell
  if [ -x "$(command -v zsh)" ]; then
    sudo chsh -s $(which zsh) $(whoami)
  fi
fi

