[settings]
disable_backends = ["asdf", "vfox"]

[tools]
node = "latest"
pnpm = "latest"
rust = "latest"

"cargo:cctx" = "latest"

"aqua:starship/starship" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:cli/cli" = "latest"
"aqua:charmbracelet/gum" = "latest"
"aqua:direnv/direnv" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"

"github:max-sixty/worktrunk" = { version = "latest", exe = "wt" }
