#! /usr/bin/env sh

set -eu

if [ "$(sudo echo hi)" != hi ]; then
  echo "Cannot use sudo."
else
  sudo apt-get update && sudo apt-get install -y \
    awscli \
    bat \
    build-essential \
    curl \
    file \
    fzf \
    git \
    grep \
    jq \
    less \
    procps \
    vim \
    zsh \
    openssh-server

  # ssd setting
  sudo mkdir /var/run/sshd
  sudo /usr/sbin/sshd

  # install other tools
  sudo env BINDIR="/usr/bin" sh -c "$(curl -fsLS get.chezmoi.io)"
  sudo env UV_INSTALL_DIR="/usr/bin" sh -c "$(curl -LsSf https://astral.sh/uv/install.sh)"
  sudo env PNPM_HOME="/usr/bin" sh -c "$(curl -LsSf https://get.pnpm.io/install.sh)"
  sudo env BIN_DIR="/usr/bin" sh -c "$(curl -sS https://starship.rs/install.sh)"
  sudo sh -c "$(curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh)" installer --repo rossmacarthur/sheldon --to /usr/bin
  sudo sh -c "curl --proto '=https' -fLsS https://github.com/eza-community/eza/releases/latest/download/eza_x86_64-unknown-linux-gnu.tar.gz | tar xz -C /usr/bin eza"

  if command -v pnpm >/dev/null 2>&1; then
    pnpm config set --location=global minimumReleaseAge 4320 # 3days
  fi

  # shell
  if command -v zsh >/dev/null 2>&1; then
    sudo chsh -s $(which zsh) $(whoami)
  fi
fi

