name: "macos"
permissions: {}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test macOS Setup
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run setup.sh
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x  # デバッグモード
          BRANCH_NAME="${{ github.head_ref || github.ref_name }}"
          URL="https://raw.githubusercontent.com/kiki-ki/dotfiles/${BRANCH_NAME}/setup.sh"
          echo "Downloading setup.sh from ${URL}"
          bash -ce "$(curl -fsSL ${URL})"

      - name: Debug - Check environment
        if: always()
        run: |
          echo "=== PATH ==="
          echo $PATH
          echo ""
          echo "=== Which chezmoi ==="
          which chezmoi || echo "chezmoi not found in PATH"
          echo ""
          echo "=== Which brew ==="
          which brew || echo "brew not found in PATH"
          echo ""
          echo "=== Check ~/.local/bin ==="
          ls -la ~/.local/bin/ 2>/dev/null || echo "~/.local/bin not found"
          echo ""
          echo "=== Home directory ==="
          ls -la ~/ | head -20
          echo ""
          echo "=== Chezmoi directory ==="
          ls -la ~/.local/share/chezmoi/ 2>/dev/null || echo "chezmoi dir not found"

      - name: Verify installation
        run: |
          set -e

          if command -v chezmoi &> /dev/null; then
            echo "ok: chezmoi installed"
          else
            echo "error: chezmoi not found"
            exit 1
          fi

          if command -v brew &> /dev/null; then
            echo "ok: Homebrew installed"
          else
            echo "error: Homebrew not found"
            exit 1
          fi

          if [ -f ~/.zshrc ]; then
            echo "ok: .zshrc exists"
          else
            echo "error: .zshrc not found"
            exit 1
          fi

          echo "ok: All verification checks passed"
